<a href="https://colab.research.google.com/github/nimitha123-kd/Take-IT-Smart-Internship/blob/main/Email_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 13/4/2026

# Email Classification

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv('email.csv')

In [ ]:
data

            Category                                            Message
0                ham  Go until jurong point, crazy.. Available only ...
1                ham                      Ok lar... Joking wif u oni...
2               spam  Free entry in 2 a wkly comp to win FA Cup fina...
3                ham  U dun say so early hor... U c already then say...
4                ham  Nah I don't think he goes to usf, he lives aro...
...              ...                                                ...
5568             ham               Will ü b going to esplanade fr home?
5569             ham  Pity, * was in mood for that. So...any other s...
5570             ham  The guy did some bitching but I acted like i'd...
5571             ham                         Rofl. Its true to its name
5572  {"mode":"full"                                    isActive:false}

[5573 rows x 2 columns]

In [ ]:
data.shape

(5573, 2)

In [ ]:
# check missing values
data.isnull().sum()

Category    0
Message     0
dtype: int64

In [ ]:
data.loc[:,'Category'].unique()

array(['ham', 'spam', '{"mode":"full"'], dtype=object)

In [ ]:
data = data[data.loc[:,'Category']!='{"mode":"full"']

In [ ]:
# replace ham--> 1 ,spam-->0
data.loc[:,'class']=data['Category'].map({'ham':1,'spam':0})

/tmp/ipykernel_3087/1762758793.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[:,'class']=data['Category'].map({'ham':1,'spam':0})

In [ ]:
data.drop(columns=['Category'],inplace=True)

/tmp/ipykernel_3087/3547669530.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(columns=['Category'],inplace=True)

In [ ]:
import re
def clean_text(text):
  text = text.lower()
  text = re.sub(r'<.*?.',"",text)
  text =re.sub(r'http\S+|www\s+','',text)
  text = re.sub(r'[^x00-\x7F]+',' ',text)
  text=re.sub(r'[^a-z0-9\s]','',text)
  text = re.sub(r'\s+',' ',text).strip()
  return text

In [ ]:
data['cleaned_text']= data['Message'].apply(clean_text)

/tmp/ipykernel_3087/2027374156.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['cleaned_text']= data['Message'].apply(clean_text)

In [ ]:
# split data for x and y
x = data['cleaned_text']
y= data['class']

In [ ]:
# split data for training and tetsing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

**CountVectorizer**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x_train_new = cv.fit_transform(x_train)
x_test_new = cv.transform(x_test)

In [ ]:
# fit_transform : learns and then transforms
# transform : no learning only transforming

#naive bayes model

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train_new,y_train)

MultinomialNB()

In [ ]:
y_pred = model.predict(x_test_new)

In [ ]:
# confusion matrix , accuracy , recall,precision,f1 score
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score

In [ ]:
confusion_matrix(y_test,y_pred)

array([[138,  11],
       [  0, 966]])

In [ ]:
accuracy_score(y_test,y_pred)

0.9901345291479821

In [ ]:
recall_score(y_test,y_pred)

1.0

In [ ]:
precision_score(y_test,y_pred)

0.9887410440122825

In [ ]:
f1_score(y_test,y_pred)

0.9943386515697376

In [ ]:
msg = input("enter the message: ")
text = cv.transform([msg])
pred = model.predict(text)
if pred[0]==0:
  print("spam")
else:
  print("Ham")

enter the message: Hello good evening, team has catch up meeting tomorrow with CEO at 11am
Ham

In [ ]:
msg = input("enter the message: ")
text = cv.transform([msg])
pred = model.predict(text)
if pred[0]==0:
  print("spam")
else:
  print("Ham")

enter the message: Hey Congratulations! you have won 1000000m$ worth prize.
spam

# TF IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
x_train_new = tf.fit_transform(x_train)
x_test_new = tf.transform(x_test)

In [ ]:
model = MultinomialNB()
model.fit(x_train_new,y_train)

MultinomialNB()

In [ ]:
y_pred = model.predict(x_test_new)

In [ ]:
confusion_matrix(y_test,y_pred)

array([[105,  44],
       [  0, 966]])

In [ ]:
accuracy_score(y_test,y_pred)

0.9605381165919282

In [ ]:
recall_score(y_test,y_pred)

1.0

In [ ]:
precision_score(y_test,y_pred)

0.9564356435643564

In [ ]:
f1_score(y_test,y_pred)

0.9777327935222672

In [ ]:
msg = input("enter the message: ")
text = cv.transform([msg])
pred = model.predict(text)
if pred[0]==0:
  print("spam")
else:
  print("Ham")

enter the message: Hi Congratulations! you have been selected for the next round of intreview with Manager.
Ham

In [ ]:
msg = input("enter the message: ")
text = cv.transform([msg])
pred = model.predict(text)
if pred[0]==0:
  print("spam")
else:
  print("Ham")

enter the message: Congratulations on winning 10000m$ worth prize
spam