<a href="https://colab.research.google.com/github/nimitha123-kd/Take-IT-Smart-Internship/blob/main/House_Price_Regression_Proj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Machine Learning Task: House Price Prediction (Regression)***

# **Problem Statement**

- The real estate industry often needs accurate estimation of property prices based on various
house characteristics. In this task, the goal is to build a Machine Learning regression model
that predicts the price of a house using features such as house size, number of bedrooms,
number of bathrooms, lot size, garage size, neighborhood quality, and the year the house was
built.


- Students are required to analyze the dataset, perform data preprocessing, apply feature
 engineering techniques, train multiple regression models, and evaluate their performance to
 identify the best model for predicting house prices.

# **Objective**

# The objective of this task is to:

 ● Understand and explore the housing dataset.

● Perform data preprocessing including handling missing values, duplicates, and outliers.

● Conduct Exploratory Data Analysis (EDA) to identify patterns and relationships in the
data.

● Apply encoding, log transformation, and feature scaling where necessary.

● Train multiple regression algorithms to predict house prices.

● Evaluate and compare model performance using appropriate evaluation metrics.

# **TASKS**

# **Import Libraries**

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
#  If any warnings are disturbing the buliding of model , then use these  libraries.
# import warnings
# warnings.filterwarnings('ignore')

# **Load Dataset**

In [5]:
# Dataset or the dataframe ==> data or df
data = pd.read_csv('house_price_regression_dataset.csv')
data

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
...,...,...,...,...,...,...,...,...
995,3261,4,1,1978,2.165110,2,10,7.014940e+05
996,3179,1,2,1999,2.977123,1,10,6.837232e+05
997,2606,4,2,1962,4.055067,0,2,5.720240e+05
998,4723,5,2,1950,1.930921,0,7,9.648653e+05
999,3268,4,2,1983,3.108790,2,2,7.425993e+05

# **Basic Checks / Check Dataset**

In [6]:
# first 5 rows
data.head()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06

In [7]:
# Last 5 rows
data.tail()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
995,3261,4,1,1978,2.165110,2,10,701493.997069
996,3179,1,2,1999,2.977123,1,10,683723.160704
997,2606,4,2,1962,4.055067,0,2,572024.023634
998,4723,5,2,1950,1.930921,0,7,964865.298639
999,3268,4,2,1983,3.108790,2,2,742599.253332

In [8]:
# Overveiw about the data frame
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Square_Footage        1000 non-null   int64
 1   Num_Bedrooms          1000 non-null   int64
 2   Num_Bathrooms         1000 non-null   int64
 3   Year_Built            1000 non-null   int64
 4   Lot_Size              1000 non-null   float64
 5   Garage_Size           1000 non-null   int64
 6   Neighborhood_Quality  1000 non-null   int64
 7   House_Price           1000 non-null   float64
dtypes: float64(2), int64(6)
memory usage: 62.6 KB

In [13]:
# Numerical Summary
data.describe()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03
mean,2815.422000,2.990000,1.973000,1986.550000,2.778087,1.022000,5.615000,6.188610e+05
std,1255.514921,1.427564,0.820332,20.632916,1.297903,0.814973,2.887059,2.535681e+05
min,503.000000,1.000000,1.000000,1950.000000,0.506058,0.000000,1.000000,1.116269e+05
25%,1749.500000,2.000000,1.000000,1969.000000,1.665946,0.000000,3.000000,4.016482e+05
50%,2862.500000,3.000000,2.000000,1986.000000,2.809740,1.000000,6.000000,6.282673e+05
75%,3849.500000,4.000000,3.000000,2004.250000,3.923317,2.000000,8.000000,8.271413e+05
max,4999.000000,5.000000,3.000000,2022.000000,4.989303,2.000000,10.000000,1.108237e+06

In [ ]:
# show only

In [10]:
# All columns
data.columns

Index(['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built',
       'Lot_Size', 'Garage_Size', 'Neighborhood_Quality', 'House_Price'],
      dtype='object')

In [12]:
# All rows / index
data.index

RangeIndex(start=0, stop=1000, step=1)

In [15]:
#Show only columns containg numericals
num_colms=data.select_dtypes(include=["float64","int64"])
num_colms

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
...,...,...,...,...,...,...,...,...
995,3261,4,1,1978,2.165110,2,10,7.014940e+05
996,3179,1,2,1999,2.977123,1,10,6.837232e+05
997,2606,4,2,1962,4.055067,0,2,5.720240e+05
998,4723,5,2,1950,1.930921,0,7,9.648653e+05
999,3268,4,2,1983,3.108790,2,2,7.425993e+05

In [16]:
# Show only columns containing / letters
cat_colms=data.select_dtypes(include=["object"])
cat_colms

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1000 rows x 0 columns]

In [18]:
# unique
for x in cat_colms:
   print(x,"--->",data[x].unique())

In [21]:
 # unique
for x in num_colms:
   print(x,"--->",data[x].unique())

Square_Footage ---> [1360 4272 3592  966 4926 3944 3671 3419  630 2185 1269 2891 2933 1684
 3885 4617 3404  974 1582 3058 2547 3247 1475 2306  689 3234 3505 2399
 1767 2028 3702 4056 4390 1146 3388 2935 1100 2863 2561  741 2541 3324
 3112 1863 1978 3056 1275 4514  534 3652 2455 2085 4443 3573 1521 3961
 3113 4343 2000  661 4797 2481 1495 3842 4298 1775 1516  837 1378 1576
 4493  879  992 2562 4384  564 3068 2527 3195 1995  891 4974 4061 2778
 3599  700 3604 2954 4145 1304 3231 3273 2070 3190 4340 1528 1002 4993
 1370 4988  706 1984 1363 3290 1063 4691 2257 2178 3742 1559 2222 3814
 3657 3125 3229 2097 3560 3193 4127 2163 2029 2538 3802 2737 1806 4529
 3175 1782 1209 4913 4248 1163 2498 3945 4243 3804 4263 2353 1791 4081
 3957 2136 4196 3499 1198 2660 4597 1354 3974 2207 3277 2233 4010  702
 3755 4718 4996 1266 4889 2827 3431  697 2430 4082 1108 3772 1647 4782
 3897 3011 2294 1159 3311 1869 2486  646 3719 3411 2234 2343  988 3476
 2459 2885 2302 4561 3869  762 1123 4143 2549 4223 3608 4590 2556 3670
 2182 2755 1654 4999 3691 2196 4491 2148 1945 4699 4423  753 3683 3057
  598 2700 3461 4933 4277 3369 3734 4291 1456 4567  660 1800 4487 2027
 1718 3235 1454 3946 1545 2193 3936 1062 2985 3854  725 1459 3567 1315
 3620  516 1743 2705 3024 1569 3065 1560 3920  801 4776 1106 1199 1639
  690 2800 1480 3475 3827 3894  627 2565 2316 1069 2395 3233 4363 3401
 2186 3509  654 3037 1909 4557 1284 3675 4841 3306 1037 2341 2955 1024
 3450 4631 4615 2868 4347 4995 3201 1471 1666 3274 2482 1353 4646 4236
 4269 1074 3761 1648 2215 4354 2991 3160 3624 3551  504 1376 1491 4642
 4864 4965 1135  619 1330 4175 1240  616 3338 1650 2431 1512 2164 1581
 1012 3349 1059 4172 3843 4570 1970 1080 2794 3647 4749 2179 4006 3244
 3856 4545 3618 2641 3559 3459 2765 2979 2135 4952 2570 3751 4230 2989
 2131 3316 1515 1848 3587 3339  835 1395 4046 1351 2187 4246 2927 2068
 4500 3238 3998 4413 1566 4880 2944 4607 3873 4469 3046 1253 2582 3396
 4685 2125 3569  917  614 1116 4474 3767 1325 2016 3646  912 1228 3848
 3308 1175 3965 3004 3467 3286 1622 4579 2071 2643 4632 4351 3940 4266
 2826 3414 4452 1095 1865 4992  895 4671 4860 3002 2319 1217 3282 4077
  643 3640 4991 3438 4136 3722 1667 3116 1562 2656 3482 3794 1656 1232
 4830 1453 3039 3824 3801 2042 1691 3493 3181 1717 2040 3736 2886 4219
 1888 2356  999 2180 1010 4812 1824 1655 2327 3641 3986 2310 3423 2714
 4686 1213 4102 4634 4022 4768 4209  955 1394 1884 2458 3572 2496 4785
 1004 1714 2031 1323 1428  633 2605 2352 4675 3433 3784 4798 1750 4012
 1756 3876 4084 1896 4137 3830 3203  970 1853 3283 3331  857 3519 1167
 4968 1645 3245 1039 3279 4636 4275 3008 1424 3456 2081 4985  755 2338
 2444  509 3371 1297 2324 4969 3636 2693  723 4658 4425 2133 2652  884
  904 2500 3256 2168 1960 3224 4678 2548 1216 2323 2581 3919 2074  749
 1173 2665 1270 4462 4863 2484 1577  735  888 3537 2348 3314 3874 3778
 1752 4481 2622 2650 1829 1858 2982 2517 1831 4844 4761 3677 2628 2680
  637 3972 3332 4079 3531 4664 3093 4800 4318 4638 4323 4542 2406 1260
 1399 4955 3447 2219  780 3766 2387 1166 4688 1171 2469 4656 3622 4400
 1023 2893 3617 2468 2253 2796 2761 2786 4702 3378 4643 4144 4932 2555
 1776 3266  802 1138  555 1025 4623 2625 3787  864 2146 1418 3297 3845
 3586 2575 2476 1796  625 4096 3783 2103  566  732 1669 2658 4706 1993
 4507 2972 3239 2261 4014 2475 2862 4312 3948 1812 3209 2824 2105 3063
 3921 4017 2897 4235 3370 1660  742 3090 1563 4824 3095 1419  505  967
 4670  503 1145  617 3428 3051 4789 1346 3262 1641 1223  724 4708 4915
 2073 2328 2417 4734 2526 4244 1401 2539  760 2173 2719 2560 4213 2119
  820 1842 2876 2494 3458 3990 4177 1618 2104 4527 4929 2408  875 4030
 3135 3060 3891 3465 4350 1372 1814 3398  577 3121 4727 1565 2636 2949
 2843 2363 1818 4097 4262 2690 1492 3212 2692 1748 3554 4533 2497 4187
 2651 4518 3610 2470 3126 1702 2535  977 1754 1422  919 2704 3097 1620
 3568 1450 2836 2743 3145 2357 2365 3412 3353 3728 2871 3391 4256 4725
  594 3174 1293 2334 2616 4606 3825 3705 1314  845 2849  862 2943 2688
 3781 1484 2139 1327 3230 4031 4951 3435 4376  626 3556 1103 3949 4033
 3867 3868 4297 2292 3361 3976 3917 2145 1705 3530 3372 2354 4521 3208
 4002 1832  701 4007 4712 1036  885 4100 4620 2490 4072 3213 2703 1466
 3932 1188 4743 4201  841 2224 4922 2259 3712 1489 2762 1451 1222 3889
 2579 3217 2832  785 3995 1268 3557 2661 3793 1446 3835 4650 1981 2401
 3951 4564  554 3962 3579 1332 4908 2990  827 3810 3800 1811 3038 4483
  664 4777 1322 1443 4925 1274 2698 3656 4742 4195 3952 1414 1808 4677
 1013 2420 4094 3690 2055 1779 1887 3261 3179 2606 4723 3268]
Num_Bedrooms ---> [2 3 1 5 4]
Num_Bathrooms ---> [1 3 2]
Year_Built ---> [1981 2016 1977 1993 1990 2012 1972 1997 2006 1982 1973 1988 1983 2005
 1986 1956 2017 2014 1996 1969 1968 1978 2009 1967 1984 1992 1960 1998
 1987 2013 2018 1957 1980 1953 1999 1979 2008 1994 1975 1976 1995 2000
 1955 1964 1991 2022 1966 1971 1962 2002 1952 1970 1950 1954 1985 2003
 1961 2019 2001 2004 2011 2021 2010 1959 2015 2020 1974 1958 1963 1965
 1989 2007 1951]
Lot_Size ---> [0.59963664 4.75301385 3.63482272 2.73066688 4.69907255 2.47593004
 4.91196007 2.80528141 1.01428596 3.94160438 3.55503976 3.97844025
 4.78148913 3.99420186 3.25101471 4.35789006 3.52960898 2.33653576
 4.48528894 1.49855207 3.71588574 4.46703555 3.79092434 3.63773939
 3.88687232 2.59274862 4.43376807 1.41546414 1.07323887 1.78478951
 2.89209829 2.79752808 4.19269441 2.32055895 2.67954992 0.56015457
 2.34382656 3.41498405 0.56978749 1.76396884 1.43580362 0.68893443
 2.6566704  1.31775482 3.84386693 4.31567548 2.95513332 4.91768304
 2.52715357 2.81015695 4.95147989 1.54196796 4.74145673 0.692769
 2.50874101 0.8150158  3.78155634 3.23784021 3.67985419 2.1851618
 2.1626687  0.70393676 2.07475223 4.68179781 2.20651942 4.24115468
 4.29046477 2.1795852  3.34394906 0.92917221 0.96655361 0.71895949
 3.11456792 2.4173194  2.9661456  2.84482936 2.07591346 3.54863037
 3.91325846 0.56582716 1.43259035 3.70956141 2.23979078 3.48117776
 2.06133197 2.25839819 1.21405493 1.66203959 3.22435291 2.449234
 3.98436207 4.3366323  2.93740888 3.91220281 1.88107031 2.36737047
 3.70749954 2.23795397 3.14827221 1.33417751 3.19897092 4.37681168
 4.40887838 3.75954983 3.85589021 3.0106735  3.13100641 1.10142762
 2.49736635 2.52849328 4.81324026 2.43989088 2.9720419  2.8996313
 3.36542773 3.86704774 1.51268844 2.87925989 4.21662968 2.58401621
 1.75305896 3.44619084 4.20695328 0.78413132 3.99555718 4.1974157
 2.57685317 4.92487546 4.04018753 3.98148154 3.86527358 1.17773646
 1.47753899 2.58795559 1.68801957 2.36858438 4.49808849 4.20947101
 3.33517945 4.36154177 4.02697575 2.43043219 1.40479318 2.81390468
 3.81302997 2.46388819 3.50047359 0.92447342 3.86602131 4.15721129
 3.68077035 4.85268614 4.21993426 4.56392178 4.70106988 4.10606596
 3.53416479 0.52573362 2.59621589 3.07023034 1.86813623 1.93147001
 4.82521737 4.51269889 4.32130552 2.32705311 0.56164348 0.86100011
 1.90488366 0.57084311 0.57717402 4.62471486 3.67771326 1.89030196
 1.0969006  2.80236073 0.52405772 4.72286185 2.36666804 2.3105073
 2.25767123 0.81197749 3.37245008 3.79851629 3.54256429 1.12295972
 3.10478076 3.06268018 4.40784855 2.20607446 2.17168675 3.28337176
 3.34882694 2.61178352 2.49376713 2.72366452 4.37470385 2.57525106
 4.72969306 2.76801694 4.77140312 4.24774356 2.13094095 4.3863864
 0.99528478 4.66271229 3.34239582 0.74475837 3.39915526 4.88411444
 0.81410295 2.99609469 3.86507457 4.14616364 2.36222359 1.41874952
 0.69054025 3.10876771 2.53809982 4.76934978 0.77272208 3.58427905
 0.612348   1.2714538  2.5411055  2.54692599 3.58565244 4.59595866
 3.37564472 4.79090794 4.46727038 3.13024908 4.25206378 3.39159925
 0.85351024 3.83254125 0.92708799 3.17337251 3.66188093 0.79937424
 1.53857594 4.62052505 3.27341522 1.60828708 3.60805897 3.18549389
 2.75709065 4.89284139 3.575542   2.18948499 4.10033044 4.48062482
 1.06349252 1.4024884  1.47302154 3.61045314 3.213678   3.28546204
 4.73347985 3.9916019  1.07571616 2.06378187 2.45927141 2.28182715
 3.51188874 4.51351896 1.87723159 2.98344711 4.0523424  2.37298126
 1.25653158 2.63727934 0.74850134 4.74072554 0.83669542 2.47305522
 2.88446567 4.93386725 1.24709821 1.01494183 0.53917766 1.20007147
 1.43272841 3.33761424 1.48868056 0.59234367 4.21978255 2.14518065
 2.09163509 1.86115563 4.88917975 1.26551938 4.54207129 3.99561499
 0.8441598  4.94028096 1.72114684 0.94362317 4.23191405 3.6800399
 3.27748463 1.20191389 2.65323252 4.01250212 1.86630772 1.90260423
 0.51413408 1.28409531 4.43932531 2.48785921 4.92905525 2.28068584
 3.71833905 1.76863569 2.13714339 1.35826694 2.06178066 2.96256884
 4.96297796 3.48890771 1.39660679 0.70232649 1.06860417 3.03149841
 3.94322148 4.73188643 0.57120427 2.85242064 2.6189031  3.4522476
 3.01810485 3.59167618 3.46137163 1.02655276 4.09873061 1.05454659
 3.64338781 2.37265415 2.81232831 4.56484106 4.50447677 4.18035338
 2.79566771 3.81307915 2.80803675 4.41322737 2.31249125 4.86605905
 4.69545241 3.83721179 1.75737148 1.09244115 4.34616553 1.24386029
 4.34417355 2.70844253 2.32950553 4.5643585  3.21732942 3.09476303
 3.01444675 2.17026282 4.03539397 1.637593   4.72502732 4.52293342
 2.01866147 3.78258696 3.07950438 2.01942186 4.94834742 0.61356806
 1.63690714 2.84033328 2.84878852 3.15019884 3.88254277 3.30565024
 3.20126657 0.74081508 2.1943863  1.54425083 1.6941655  2.99451863
 1.39777392 1.82277095 1.56688119 4.76826324 4.75099579 3.24473701
 4.66035111 4.0361569  3.15476547 0.52895845 3.97632329 3.66119754
 3.26864144 3.9219094  2.80814974 3.66837472 4.70827439 2.19112257
 3.68654826 2.64059518 3.53479843 3.93302001 0.70453625 3.409702
 1.52033533 3.51514642 2.60748584 3.98098734 1.05530367 3.31845058
 1.75311828 4.33841898 4.67772578 4.98379232 4.08203331 3.89180332
 1.46975341 2.01203177 2.59557144 3.98021472 4.61734639 1.35112595
 4.65065368 3.63031094 3.24846829 1.39928572 0.74986265 3.05809204
 3.43182057 1.44851652 3.00405293 4.35422031 4.25779675 4.67309831
 2.14648614 1.93122308 3.87241703 2.44000582 0.89396899 1.77260509
 2.38362028 1.81632391 1.99492507 1.82199158 0.68674625 3.36692615
 3.18781589 3.44022574 1.36539453 1.83044544 3.28827167 3.19832406
 2.77848639 2.07685963 4.60818952 2.02896609 2.5502862  3.55151224
 2.94359644 2.06098689 2.46040156 4.07516368 1.7515812  1.14014858
 1.90923441 4.32290397 0.90045372 4.96263233 2.93451305 4.93180585
 4.7254839  2.53766171 1.39320984 1.24198149 1.57995214 3.69559688
 1.72827498 2.03641371 2.51950462 4.60954706 1.35227038 0.52261949
 0.77043385 4.57144854 3.41382409 1.72868279 1.29736625 1.82420031
 1.01658617 4.7368981  4.02892778 2.5807603  4.39233172 1.62256192
 3.72704256 4.35259625 2.1054592  3.90859    1.82782557 1.84485711
 0.9817573  2.48026121 3.78370358 4.73099363 3.21708646 4.38410992
 4.20122592 1.28004374 2.68617843 1.02615591 3.56968923 4.77454851
 1.11690256 3.80247409 3.34507168 3.12622267 2.25554106 2.09809241
 0.70362135 1.48058919 0.56829597 3.11637698 0.97633956 4.42858727
 2.85414359 3.64860459 2.34885691 3.02260914 4.7419663  0.87230318
 1.64271997 4.00994747 0.94431743 0.84047497 2.12693629 0.91475581
 3.13285299 1.51823863 4.53064083 4.02575036 3.64867343 3.27624812
 4.38559579 1.50377928 4.42898979 4.05271534 3.86672372 3.02565055
 1.60809872 2.40596562 4.07106795 0.64300318 4.01922846 1.58031833
 1.1493914  1.02065593 0.62262505 2.85613918 1.48216943 4.95244295
 3.0849654  1.12048371 3.59943143 4.53984605 3.85330773 0.84397937
 4.53147882 4.07268224 1.21236755 0.7330365  3.00789759 1.20216115
 4.25565929 2.11250596 4.608016   3.04559677 1.32202573 1.1281949
 3.09412597 3.92847625 4.01677541 1.74090832 1.41911042 0.57540337
 3.55639618 0.84455716 2.39342541 3.20756974 4.71699025 1.90310962
 1.62397473 3.44372069 3.28657564 1.99449402 4.67645826 4.30188047
 1.50792146 1.57614145 2.80535156 3.98107446 0.69818171 3.62000819
 3.41706154 1.54166043 3.56608856 4.73082436 0.7105363  1.93843425
 2.47179522 4.54667162 4.83017651 2.49851861 3.87512785 2.89247461
 2.92002321 1.75144782 1.47630311 1.79602406 3.00347603 0.63119834
 4.58262025 1.20327669 1.49039905 2.83224279 3.69551645 0.93078075
 1.92962614 4.85903573 1.68054335 1.90872565 4.26424321 0.72596494
 2.59075926 2.20827544 1.92464042 1.78564817 0.91118347 1.91671623
 0.69373581 4.01433739 2.29202507 2.49756725 4.52117564 3.46124743
 0.53626597 4.7442867  1.5671501  0.98426383 3.9565768  2.75214792
 2.45196755 1.62276386 2.9636217  1.73473072 4.55712352 1.46842016
 4.47959818 3.01732442 4.2281966  3.70780698 3.635128   1.95955613
 1.55253619 1.44898802 4.35736246 4.19192069 2.48258088 1.09582076
 2.22013513 3.28704554 2.5448142  4.01085171 4.9893027  1.3600944
 2.56842869 2.43942756 1.8702164  1.39142983 0.79561452 4.49203693
 2.38931914 2.73602983 4.62623922 3.99330715 1.08725569 3.04438985
 2.49013524 4.08744983 3.75904646 3.60682575 2.03245176 4.12233679
 0.73576083 1.21831206 2.01030473 0.84563348 1.55747425 4.23567942
 4.76713192 1.8707106  1.69032112 1.75951694 1.74973589 0.66168582
 4.67112356 1.46164164 2.39001833 0.54359097 4.36079791 3.79020805
 4.76040216 4.01726966 1.9116793  1.61543011 3.63972338 2.13850749
 3.04796757 0.52815862 0.77848566 2.90915574 3.04732241 3.88153825
 1.09384394 2.80932388 1.3750144  0.91938254 2.34723107 1.23501492
 1.4980189  1.92899561 1.6672478  0.89416084 0.9046231  1.36962237
 0.72751635 3.31905659 1.79297022 1.75885685 1.99399232 3.48258323
 4.41785247 3.9158912  3.77388154 2.67976034 3.62212501 2.98743066
 1.47312738 1.43864765 1.83376403 4.59861202 2.96336678 3.8025742
 2.05951442 2.33472097 1.0650451  1.27082731 4.2231045  3.13177384
 2.0188961  4.11283044 1.60933958 4.89214714 2.05167923 2.01789929
 1.90360357 1.04950182 1.00011716 3.41647266 4.4380312  4.0573423
 1.13498417 2.95511955 0.97516196 0.7038259  3.45373637 2.9081855
 0.86910658 0.65722661 4.95390386 0.63509599 2.50037714 2.77078561
 1.02776067 1.260778   2.08312253 3.92754144 2.78187091 3.37055844
 4.9332855  3.95602446 2.45462674 2.50898865 3.28447435 3.49414344
 2.75319917 3.4018755  0.60589622 2.43330289 1.75522134 1.081285
 0.94795931 3.21436475 2.85620246 1.64112853 2.61927526 2.71504542
 1.37754041 3.43441878 4.0141371  4.06158593 3.21111424 2.80237362
 0.77453214 1.79524084 0.91972151 4.83720422 1.10786066 1.18298934
 4.50309478 4.74767728 3.94623068 0.52432216 0.50605822 2.20145346
 1.14527917 0.58273764 2.5883001  4.74377854 1.95718809 3.47513305
 3.43505909 1.62986047 3.42691362 1.45550288 1.04903336 3.65622479
 1.01048368 4.98609148 1.32553581 3.17363838 2.35118557 1.0687389
 0.62529758 3.30229527 4.13040904 4.28907048 2.67221063 3.9985496
 3.5278121  3.75914537 2.71669552 3.35035283 4.12486661 2.29047879
 4.12690505 3.16407579 1.24655461 0.61107871 2.1323912  2.96013348
 4.27919158 1.07368556 4.10092856 4.38354071 1.17809369 4.33217444
 4.96154106 3.77077474 4.03146357 4.9748687  3.22466563 1.88548872
 4.26888875 3.265186   3.11537941 1.64136    3.90350421 0.86750274
 4.65929182 1.96620557 1.07498594 2.4906494  0.69111459 3.58081787
 4.5621748  4.26768353 1.07316263 1.06822012 4.16045517 4.65914424
 2.57301423 2.74537003 1.93217919 4.52419303 3.40206307 1.7971321
 1.84452292 4.51040033 0.56135311 1.95226958 2.99460507 1.16697858
 0.91444439 4.16874349 4.52481975 4.20622889 4.5445455  2.98900387
 4.15516154 2.22819187 3.49820538 4.94975989 1.51577476 2.25454886
 2.6602132  1.12106969 0.86467375 4.2337529  4.89557468 2.32126279
 0.89442426 0.79615292 4.51093193 2.58716412 1.94012292 2.64407572
 1.93236843 2.70066099 4.36800379 3.16535617 3.62594198 2.14101804
 3.82327645 3.49977688 1.03802899 3.07689284 1.65534573 4.11843051
 2.41671969 4.97607874 0.91625197 4.01156538 3.5316578  3.95374474
 1.88388408 2.7142452  4.08428834 1.54643599 1.51714939 2.97972929
 2.85603611 1.77018112 1.84134043 1.75030323 3.97180428 3.4335539
 4.24587733 4.88962863 2.63373933 0.80012247 0.7164154  1.83049268
 4.69645065 2.85445875 1.72303932 2.29625058 3.19367798 3.43827346
 1.19263779 4.89664254 2.95147502 1.11059743 4.52135864 0.83587294
 4.58480945 4.98454545 3.6519431  3.96701249 2.01786276 4.73709584
 2.88371285 3.79574801 4.65848472 4.88830989 4.2494196  1.86357878
 4.84946382 3.32653789 4.68789114 3.54247262 1.88257533 2.16511036
 2.977123   4.05506679 1.93092148 3.10879025]
Garage_Size ---> [0 1 2]
Neighborhood_Quality ---> [ 5  6  9  8  1  2  4 10  7  3]
House_Price ---> [ 262382.85227406  985260.85449016  777977.39011858  229698.91866361
 1041740.8589249   879796.98352238  814427.86140899  703413.11094468
  173875.03721558  504176.50605937  335332.59275294  635097.3959198
  701133.80414712  440726.28481629  838719.4305035  1019192.6613592
  735850.81234216  234261.64997474  396246.35888875  672852.051981
  586086.56853891  740174.01465508  370167.09090272  530824.19677521
  227515.30028798  652166.14236589  745670.63714772  513161.95119306
  432357.90610274  434165.89663405  809686.20114353  883819.09112186
  912468.04790467  281313.06144485  705923.31489162  656980.46042822
  318266.27713209  582468.79773652  541967.63355925  188531.42345711
  565562.75043214  697574.55566703  666733.47346169  376388.02162864
  485380.95019563  735678.46220173  296291.00100751 1046315.89601366
  187508.58531168  793995.28487578  527393.51288759  467768.12294397
  981190.78291122  750481.71693516  377511.26849809  866877.3524151
  731331.66105671  899382.86515848  485622.40191999  147601.55157708
  986006.86173676  509725.55065509  346932.62090089  863289.39690309
  919295.85406152  406069.27091275  397346.11087768  191117.10122305
  384461.35482616  340980.72481778  951093.54699385  217010.48526715
  248224.0196561   538349.09621518  985223.99665419  242865.93150163
  654466.94540868  551967.88826688  663904.9927178   397482.74798704
  209632.8414775  1107045.06293508  787420.40407499  605371.70471706
  721018.06390314  199066.37891067  730047.49738813  627923.61719947
  898283.88673564  277832.10571177  731490.11753309  688357.64848033
  525582.31022146  684824.53486344  903251.94056094  323118.73931523
  307101.68583856 1020324.75659665  304730.506229   1026397.29661223
  199414.94263281  472657.61431723  340069.22977593  696709.41528905
  266533.05392412  971514.76204285  501305.54899407  480961.44203832
  758977.88186757  364658.52862084  515813.75783539  834587.51177366
  747384.06080821  667696.04497352  645145.53984686  481368.12552157
  740148.19377686  639073.18424154  886568.31322771  450941.13543726
  513720.44181706  521205.60097671  455122.09995895  551463.88885341
  816173.75242649  637736.01039999  420203.46155751 1026790.06632797
  744681.39706346  400585.46235503  368327.45671832  977158.592318
  883626.62038572  244030.40713359  558598.67876143  860329.49231099
  947490.77747782  492018.32279508  832386.33119584  893926.62947207
  534464.9120088   355281.41848529  834105.79434011  885550.38262565
  551859.08569476  922420.5883706   804433.80932186  734985.063047
  346152.84759213  649973.36186814 1006939.66441741  370260.60316679
  928059.71295337  492112.03971497  752466.67466662  573797.93930685
  854876.29837392  183663.64645732  788150.93181063  981510.89525884
 1070454.27524761  241968.84326654 1064004.87257921  640767.22415134
  762159.39147334  216591.97111921  497168.08834548  857205.24526539
  285546.50168492  819125.64705443  316130.25555761 1067425.21662132
  837398.56514356  658260.70601105  475767.3504504   250101.54733055
  688516.50466909  510876.99909322  543734.42189014  146406.89625235
  828512.10195891  719969.43529451  507847.58733911  507554.94405352
  294558.07202157  712212.21541028  491715.94766366  625227.04547012
  752101.90242076  501913.64710804  907358.63299571  878704.09563971
  237070.7057046   267132.41358482  353129.56847341  845141.61666389
  656223.16273053  884677.68907983  775773.2237663   918893.74392356
  607698.7371082   838774.48403911  470978.4795329   616308.9624199
  417416.26225428 1060976.48857231  809046.28417627  485376.42332358
  965816.66811073  517515.4060051   438250.17615462 1008240.78543549
  888140.07598706  252963.35620761  801206.20367019  624112.16002046

In [20]:
# value counts
for x in num_colms:
  print(data[x].value_counts())

Square_Footage
3419    3
4219    3
4646    3
1743    3
2292    2
       ..
1269    1
4926    1
966     1
3592    1
4272    1
Name: count, Length: 894, dtype: int64
Num_Bedrooms
2    215
5    205
1    201
4    197
3    182
Name: count, dtype: int64
Num_Bathrooms
1    350
2    327
3    323
Name: count, dtype: int64
Year_Built
1996    24
1977    22
2008    21
1983    21
2017    21
        ..
1980     8
2001     8
2020     8
1951     6
1963     5
Name: count, Length: 73, dtype: int64
Lot_Size
3.108790    1
0.599637    1
4.753014    1
3.634823    1
2.730667    1
           ..
4.781489    1
3.978440    1
3.555040    1
3.941604    1
1.014286    1
Name: count, Length: 1000, dtype: int64
Garage_Size
2    343
1    336
0    321
Name: count, dtype: int64
Neighborhood_Quality
10    123
5     109
2     105
7     102
6     101
4      99
8      97
1      91
9      88
3      85
Name: count, dtype: int64
House_Price
742599.253332    1
262382.852274    1
985260.854490    1
777977.390119    1
229698.918664    1
                ..
701133.804147    1
635097.395920    1
335332.592753    1
504176.506059    1
173875.037216    1
Name: count, Length: 1000, dtype: int64

In [22]:
# Value count
for x in cat_colms:
  print(data[x].value_counts())

# **Handle Missing Values**

In [24]:
data.isnull().sum()

Square_Footage          0
Num_Bedrooms            0
Num_Bathrooms           0
Year_Built              0
Lot_Size                0
Garage_Size             0
Neighborhood_Quality    0
House_Price             0
dtype: int64

# **Remove Duplicate Records**

In [25]:
data.duplicated().sum()

np.int64(0)

# **Exploratory Data Analysis**


- Univariate